### ISSUE TITLE
InvalidResponseException on `places` and `geocode`

### ISSUE THREAD

**Issue by cyc115** [zilverline/google-maps#18]
👋  Hi there! Thanks for the gem! Looks like google might have made some breaking changes to the api and the library is currently half broken. For example calling `geocode` and `places` as shown in readme will result in an error. 
 
```
 geocodes = Google::Maps.geocode("Science Park, Amsterdam")
Google::Maps::InvalidResponseException: unknown error: getaddrinfo: nodename nor servname provided, or not known (nil-uri-given:80)
from /Users/yuecchen/.rvm/gems/ruby-2.5.3/gems/google-maps-3.0.4/lib/google_maps/api.rb:64:in `rescue in response'
Caused by SocketError: getaddrinfo: nodename nor servname provided, or not known (nil-uri-given:80)
from /Users/yuecchen/.rvm/gems/ruby-2.5.3/gems/httpclient-2.8.3/lib/httpclient/session.rb:625:in `rescue in create_socket'
Caused by SocketError: getaddrinfo: nodename nor servname provided, or not known
from /Users/yuecchen/.rvm/gems/ruby-2.5.3/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `initialize'
```

**Comment by Ruben-Hartog** [comment]
It seems like your configuration is incorrect. The call you are making is working for me.

Please check the README for the required configuration, because it has changed for the 3.x versions.

**Comment by trollfred** [comment]
```
Status code Unknown from https://maps.googleapis.com/maps/api/geocode/json: 
ERROR - HTTPSConnectionPool(host='maps.googleapis.com', port=443): 
Max retries exceeded with url: /maps/api/geocode/json?address=...&bounds=&components=&region=&language=&key=...
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x110151580>:
Failed to establish a new connection:
[Errno 8] nodename nor servname provided, or not known'))
```
This is happening after sending about a hundred requests in a row
Then it just always returns this error 🤔

**Comment by aames-cls** [comment]
this is also happening to me as well, no matter which Google request I send

```ruby
irb(main):032:0> Google::Maps.distance("Science Park, Amsterdam", "Deventer")
Traceback (most recent call last):
        2: from (irb):31:in `<main>'
        1: from (irb):32:in `rescue in <main>'
Google::Maps::InvalidResponseException (unknown error: getaddrinfo: Name does not resolve (nil-uri-given:80))
irb(main):033:0>  Google::Maps.duration("Science Park, Amsterdam", "Deventer")
Traceback (most recent call last):
        2: from (irb):32:in `<main>'
        1: from (irb):33:in `rescue in <main>'
Google::Maps::InvalidResponseException (unknown error: getaddrinfo: Name does not resolve (nil-uri-given:80))
```

I'm even using the README's examples.. I have enabled Directions, Places, Geolocation, Geocoding, etc. on my Google Console as well. is there a reason this is happening?
